[theme]
# Configuración del tema (Dark/Light)
base = "light"

# Colores del tema
primaryColor = "#1f77b4"
backgroundColor = "#9BADA9"
secondaryBackgroundColor = "#00ff30"
textColor = "#ffff00"
font = "sans serif"

