[theme]
# Configuración del tema (Dark/Light)


# Colores del tema
primaryColor = "#1f77b4"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#00ff30"
textColor = "#ffff00"
font = "sans serif"

