[theme]
# Configuración del tema (Dark/Light)
base = "light"

# Colores del tema
primaryColor = "#1f77b4"
backgroundColor = "#9BADA9"
secondaryBackgroundColor = "#4C6B6C"
textColor = "#000000"
font = "sans serif"

